version: '3.1'
services:
    mongodb:
        container_name: mongodb-${API_NAME}
        image: mongo:latest
        restart: always
        command: mongod --port ${MONGODB_PORT}
        ports:
            - ${MONGODB_PORT}:27017
        environment:
            MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        env_file:
            - .env
        volumes:
            - ./docker/mongodb/entrypoints/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./docker/mongodb/data:/data/db
